spring.application.name=spring-mcp-gateway
spring.ai.mcp.server.protocol=STREAMABLE
management.tracing.sampling.probability=1.0
rag.base-url=${RAG_BASE_URL:http://localhost:8000}
rag.connection-timeout=4s
rag.read-timeout=60s

management.otlp.metrics.export.enabled=${OTEL_METRICS_EXPORT_ENABLED:false}
management.tracing.export.otlp.enabled=${OTEL_TRACING_EXPORT_ENABLED:false}
